// Generated by CoffeeScript 1.6.3
(function() {
  var NODE_ENV, express, fs, path, web;

  path = require('path');

  require(path.join(__dirname, './env'));

  NODE_ENV = process.env.NODE_ENV || 'development';

  fs = require('fs');

  express = require('express');

  web = express();

  web.set('title', 'putio');

  web.set('port', process.env.PORT || 5000);

  if (NODE_ENV === 'development') {
    require('node-pow')(web);
    require('./asset_routes')(web);
  } else {
    require('./assets').precompile();
  }

  web.use(express["static"](__dirname + '/public'));

  if (NODE_ENV !== 'development') {
    web.get('*', function(request, response) {
      return fs.createReadStream('./public/app.html').pipe(response);
    });
  }

  web.listen(web.get('port'), function() {
    return console.log("Node app is running at http://localhost:" + web.get('port'));
  });

}).call(this);

/*
//@ sourceMappingURL=web_server.map
*/
